openapi: 3.0.3
info:
  title: 'Curso Beta API | By Vinicius'
  description: 'Documentation related to the API of the Beta Course'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/accounts:
    get:
      summary: 'Get all bank accounts'
      operationId: getAllBankAccounts
      description: ''
      parameters:
        -
          in: query
          name: search
          description: 'Search term.'
          example: John
          required: false
          schema:
            type: string
            description: 'Search term.'
            example: John
        -
          in: query
          name: sortBy
          description: 'Column to sort by.'
          example: created_at
          required: false
          schema:
            type: string
            description: 'Column to sort by.'
            example: created_at
        -
          in: query
          name: sortDirection
          description: 'Sort direction.'
          example: asc
          required: false
          schema:
            type: string
            description: 'Sort direction.'
            example: asc
        -
          in: query
          name: page
          description: 'Number of items per page.'
          example: 1
          required: false
          schema:
            type: integer
            description: 'Number of items per page.'
            example: 1
        -
          in: query
          name: take
          description: 'Number of items to take.'
          example: 10
          required: false
          schema:
            type: integer
            description: 'Number of items to take.'
            example: 10
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  headerCode: 200
                  content:
                    status: true
                    message: 'Records found'
                    data:
                      current_page: 1
                      data:
                        -
                          id: 1
                          name: 'John Doe'
                          balance: '1000.00'
                          created_at: '2024-02-29T02:32:24.000000Z'
                          updated_at: '2024-02-29T03:42:11.000000Z'
                      first_page_url: 'http://localhost/api/accounts?page=1'
                      from: 1
                      last_page: 1
                      last_page_url: 'http://localhost/api/accounts?page=1'
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: 'http://localhost/api/accounts?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      next_page_url: null
                      path: 'http://localhost/api/accounts'
                      per_page: 10
                      prev_page_url: null
                      to: 1
                      total: 1
                properties:
                  headerCode:
                    type: integer
                    example: 200
                  content:
                    type: object
                    properties:
                      status:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: 'Records found'
                      data:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 1
                          data:
                            type: array
                            example:
                              -
                                id: 1
                                name: 'John Doe'
                                balance: '1000.00'
                                created_at: '2024-02-29T02:32:24.000000Z'
                                updated_at: '2024-02-29T03:42:11.000000Z'
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1
                                name:
                                  type: string
                                  example: 'John Doe'
                                balance:
                                  type: string
                                  example: '1000.00'
                                created_at:
                                  type: string
                                  example: '2024-02-29T02:32:24.000000Z'
                                updated_at:
                                  type: string
                                  example: '2024-02-29T03:42:11.000000Z'
                          first_page_url:
                            type: string
                            example: 'http://localhost/api/accounts?page=1'
                          from:
                            type: integer
                            example: 1
                          last_page:
                            type: integer
                            example: 1
                          last_page_url:
                            type: string
                            example: 'http://localhost/api/accounts?page=1'
                          links:
                            type: array
                            example:
                              -
                                url: null
                                label: '&laquo; Previous'
                                active: false
                              -
                                url: 'http://localhost/api/accounts?page=1'
                                label: '1'
                                active: true
                              -
                                url: null
                                label: 'Next &raquo;'
                                active: false
                            items:
                              type: object
                              properties:
                                url:
                                  type: string
                                  example: null
                                label:
                                  type: string
                                  example: '&laquo; Previous'
                                active:
                                  type: boolean
                                  example: false
                          next_page_url:
                            type: string
                            example: null
                          path:
                            type: string
                            example: 'http://localhost/api/accounts'
                          per_page:
                            type: integer
                            example: 10
                          prev_page_url:
                            type: string
                            example: null
                          to:
                            type: integer
                            example: 1
                          total:
                            type: integer
                            example: 1
      tags:
        - 'Bank account management'
      security: []
    post:
      summary: 'Create a new bank account'
      operationId: createANewBankAccount
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Bank account management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Name of the account.'
                  example: 'John Doe'
                balance:
                  type: numeric
                  description: 'Initial balance of the account.'
                  example: '1000'
              required:
                - name
                - balance
      security: []
  '/api/accounts/{id}':
    get:
      summary: 'Get a bank account'
      operationId: getABankAccount
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  headerCode: 200
                  content:
                    status: true
                    message: 'Account found'
                    data:
                      id: 1
                      name: 'John Doe'
                      balance: '1000.00'
                      created_at: '2024-02-29T02:32:24.000000Z'
                      updated_at: '2024-02-29T03:42:11.000000Z'
                properties:
                  headerCode:
                    type: integer
                    example: 200
                  content:
                    type: object
                    properties:
                      status:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: 'Account found'
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: 'John Doe'
                          balance:
                            type: string
                            example: '1000.00'
                          created_at:
                            type: string
                            example: '2024-02-29T02:32:24.000000Z'
                          updated_at:
                            type: string
                            example: '2024-02-29T03:42:11.000000Z'
      tags:
        - 'Bank account management'
      security: []
    put:
      summary: 'Update a bank account'
      operationId: updateABankAccount
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Bank account management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Name of the account.'
                  example: 'John Doe'
                balance:
                  type: numeric
                  description: 'Initial balance of the account.'
                  example: '1000'
              required:
                - name
                - balance
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the account.'
        example: 1
        required: true
        schema:
          type: integer
  /api/transactions:
    post:
      summary: "Transaction\nMake a transaction between two bank accounts"
      operationId: transactionMakeATransactionBetweenTwoBankAccounts
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Transaction authorized'
                  status: 200
                  data: []
                  type: success
                properties:
                  message:
                    type: string
                    example: 'Transaction authorized'
                  status:
                    type: integer
                    example: 200
                  data:
                    type: array
                    example: []
                  type:
                    type: string
                    example: success
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Insufficient balance'
                  status: 401
                  data: []
                  type: error
                properties:
                  message:
                    type: string
                    example: 'Insufficient balance'
                  status:
                    type: integer
                    example: 401
                  data:
                    type: array
                    example: []
                  type:
                    type: string
                    example: error
      tags:
        - 'Transaction management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: 'The amount to be transferred.'
                  example: 100.0
                sender:
                  type: integer
                  description: 'The id of the sender bank account.'
                  example: 1
                receiver:
                  type: integer
                  description: 'The id of the receiver bank account.'
                  example: 2
                scheduled:
                  type: boolean
                  description: 'optional If the transaction is scheduled.'
                  example: true
                data_scheduled:
                  type: date
                  description: 'optional The date of the scheduled transaction.'
                  example: '2024-02-29'
              required:
                - amount
                - sender
                - receiver
      security: []
tags:
  -
    name: 'Bank account management'
    description: 'APIs for managing bank accounts'
  -
    name: 'Transaction management'
    description: 'APIs for managing transactions'
